### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Joao620** [xrelkd/clipcat#32] opened 2023-10-16 00:32 UTC
```
error: failed to run custom build command for `librocksdb-sys v6.11.4`

Caused by:
  process didn't exit successfully: `/home/joao/.cache/yay/clipcat/src/clipcat-0.5.0/target/release/build/librocksdb-sys-f9504d1500bb116a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/joao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.24/src/fallback.rs:693:9:
  "enum_(unnamed_at_rocksdb/include/rocksdb/c_h_722_1)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==> ERROR: A failure occurred in package().
/usr/share/makepkg/util/message.sh: line 51: QUIET: unbound variable
 -> error making: clipcat-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
clipcat - exit status 1
Exception: yay exited with 1
[tty 10]:1:1: yay -S clipcat
```

please let me know of commands to show more of my system info and give more context of the error

**Comment by xrelkd** [comment] 2023-11-25 09:12
The issue is fixed by https://github.com/xrelkd/clipcat/pull/39.
`Clipcat` does not dependent on `rocksdb` now.

**Closed by xrelkd** 2023-11-25 09:12 UTC
